# Generated by Django 2.0.2 on 2018-04-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ldl/carousal/')),
                ('descriptionHead', models.TextField(default='', max_length=50)),
                ('descriptionBody', models.TextField(default='', max_length=100)),
                ('registerText', models.CharField(default='', max_length=50)),
                ('link', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Core',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('branch', models.CharField(choices=[('CSE', 'CSE'), ('IT', 'IT'), ('ECE', 'ECE'), ('ME', 'ME'), ('EEE', 'EEE'), ('MBA', 'MBA'), ('MCA', 'MCA'), ('B.Pharma', 'B.Pharma')], default='CSE', max_length=10)),
                ('year', models.CharField(choices=[('First Year', 'I'), ('Second Year', 'II'), ('Third Year', 'III'), ('Fourth Year', 'IV')], default='', max_length=15)),
                ('image', models.ImageField(upload_to='ldl/core/')),
            ],
        ),
        migrations.CreateModel(
            name='Fame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('branch', models.CharField(choices=[('CSE', 'CSE'), ('IT', 'IT'), ('ECE', 'ECE'), ('ME', 'ME'), ('EEE', 'EEE'), ('MBA', 'MBA'), ('MCA', 'MCA'), ('B.Pharma', 'B.Pharma')], default='CSE', max_length=10)),
                ('year', models.CharField(choices=[('First Year', 'I'), ('Second Year', 'II'), ('Third Year', 'III'), ('Fourth Year', 'IV')], default='', max_length=15)),
                ('image', models.ImageField(upload_to='ldl/fame/')),
                ('description', models.TextField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='news',
            name='link',
        ),
        migrations.AddField(
            model_name='news',
            name='pdf',
            field=models.FileField(blank=True, upload_to='ldl/circular/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='circular',
            field=models.TextField(max_length=300),
        ),
    ]
