# Generated by Django 2.0.2 on 2018-04-28 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0002_carousal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='birds/fame/')),
                ('description', models.TextField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='carousal',
            name='description',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carousal',
            name='link',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='carousal',
            name='image',
            field=models.ImageField(upload_to='birds/carousal/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='circular',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='news',
            name='link',
            field=models.FileField(upload_to='birds/circular/'),
        ),
    ]
