# Generated by Django 2.0.2 on 2018-04-28 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0003_auto_20180429_0236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='link',
            new_name='pdf',
        ),
    ]
