# Generated by Django 2.0.2 on 2018-04-28 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0004_auto_20180429_0238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carousal',
            old_name='description',
            new_name='descriptionHead',
        ),
        migrations.AddField(
            model_name='carousal',
            name='descriptionBody',
            field=models.TextField(default='', max_length=100),
        ),
    ]
