# Generated by Django 2.0.2 on 2018-04-28 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0006_carousal_registertext'),
    ]

    operations = [
        migrations.AddField(
            model_name='fame',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
