# Generated by Django 2.0.2 on 2018-04-28 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0007_fame_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Core',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='birds/core/')),
            ],
        ),
    ]
