# Generated by Django 2.0.2 on 2018-04-30 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0008_core'),
    ]

    operations = [
        migrations.AddField(
            model_name='core',
            name='branch',
            field=models.CharField(choices=[('CSE', 'CSE'), ('IT', 'IT'), ('ECE', 'ECE'), ('ME', 'ME')], default='CSE', max_length=5),
        ),
    ]
