# Generated by Django 2.0.2 on 2018-04-30 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0011_auto_20180430_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='fame',
            name='year',
            field=models.CharField(choices=[('First Year', 'I'), ('Second Year', 'II'), ('Third Year', 'III'), ('Fourth Year', 'IV')], default='', max_length=15),
        ),
    ]
