# Generated by Django 2.0.2 on 2018-08-23 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carousal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='home/carousal/')),
                ('descriptionHead', models.TextField(default='', max_length=50)),
                ('descriptionBody', models.TextField(default='', max_length=100)),
                ('registerText', models.CharField(default='', max_length=50)),
                ('link', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
